package com.copperleaf.ballast.queue

import kotlinx.coroutines.flow.Flow
import kotlin.time.Duration
import kotlin.time.Duration.Companion.minutes
import kotlin.time.Duration.Companion.seconds

/**
 * The QueueDriver interface defines the operations that a persistent job queue driver must implement in order to
 * support enqueuing, processing, and tracking jobs. It is a low level API responsible only for the persistent storage
 * of jobs and generating a Flow for processing those jobs.
 */
public interface QueueDriver<JobMetadata : Any> {

// Insert/Query Operations
// ---------------------------------------------------------------------------------------------------------------------

    /**
     * Adds an item to the queue. All properties of a [SerializedJob] must be provided except for the ID, which will be
     * generated by the driver and returned to the caller. The job is inserted into a specific queue by name.
     *
     * This function should return a String representation of the job's unique ID.
     */
    public suspend fun addToQueue(
        queueName: String,
        serializedPayload: String,
        serializedInitialState: String,
        timeoutDuration: Duration,
        metadata: JobMetadata,
    ): String

    /**
     * Observe a flow of jobs from the queue. Items emitted to the flow should not be removed from the queue, since its
     * state of the job will be updated in-place.
     */
    public fun observeQueue(
        queueName: String,
    ): Flow<SerializedJob<JobMetadata>>

// Job Processing State/Results
// ---------------------------------------------------------------------------------------------------------------------

    /**
     * The job state was updated while processing the job. If a job is retried, the state will be maintained between attempts.
     */
    public suspend fun updateJobState(
        jobId: String,
        serializedState: String,
    )

    /**
     * The job ran to completion successfully.
     */
    public suspend fun completeJobSuccessfully(
        jobId: String,
        processingTime: Duration,
        resultType: JobCompletionResultType,
        serializedResultData: String?,
    )

    /**
     * The job failed to complete. The processing time and result are provided so the driver can update the job record
     * appropriately, and optionally enqueue it for retry at a later time.
     */
    public suspend fun completeJobWithFailure(
        jobId: String,
        processingTime: Duration,
        resultType: JobCompletionResultType,
        retryDelay: Duration,
        permanentlyFail: Boolean,
        skipAttempt: Boolean,
        failureMessage: String?,
        failureStacktrace: String?,
    )

// Cancellation
// ---------------------------------------------------------------------------------------------------------------------

    /**
     * Request job cancellation
     */
    public suspend fun requestJobCancellation(jobId: String)

    /**
     * Listen for events from the driver to know when a job was cancelled
     */
    public fun subscribeToJobCancellation(jobId: String): Flow<Unit>

// Shutdown
// ---------------------------------------------------------------------------------------------------------------------

    /**
     * Signal that the queue should shut down gracefully. Drivers that use a [QueueThrottle] should delegate to
     * [QueueThrottle.awaitShutdown] so that all in-flight jobs are allowed to finish before this method returns.
     */
    public suspend fun awaitShutdown() {}

    public interface Adapter<
            JobMetadata : Any,
            Payload : Any,
            Result : Any,
            State : Any,
            > {

        /**
         * Get the timeout duration for the given job payload. This is how long the job has to complete before it is
         * forcibly cancelled and marked as a failure. It may be retried according to the driver's retry policy.
         *
         * This is called when inserting a new job into the queue.
         */
        public fun getJobTimeout(payload: Payload): Duration {
            return 30.seconds
        }

        /**
         * Convert the payload into job metadata to be stored alongside the job in the queue. The metadata is not used
         * by the [QueueExecutor] itself, but is needed [QueueDriver] implementation to determine how and when to
         * enqueue and dequeue the job. Common data the Driver might store in the Metadata includes things like:
         *
         * - Initial delay
         * - Number of times the job has already run
         * - Max number of retry attempts before marking the job as permanently failed
         * - Timestamps for when the job was inserted, last attempted, next available run time, etc.
         *
         * This is called when inserting a new job into the queue.
         */
        public fun getJobMetadata(payload: Payload): JobMetadata

        /**
         * Called after a job failed and is being retried, to determine how long to wait before making the job
         * available to run again. The default implementation returns 1 minute. The [metadata] can be used to apply
         * custom retry backoff strategies based on the number of attempts or other data stored by the [QueueDriver].
         *
         * Jobs may instead throw [com.copperleaf.ballast.queue.executor.JobFailureException] during processing to
         * request a specific delay that was determined at runtime, rather than using this default value. That would be
         * common in scenarios such as network rate-limiting, where the server response indicates how long to wait.
         */
        public fun getDefaultRetryDelayTimeout(payload: Payload, attempts: Int): Duration {
            return 1.minutes
        }
    }
}
