package com.copperleaf.ballast.queue

import kotlinx.coroutines.flow.Flow
import kotlin.time.Duration

/**
 * The QueueDriver interface defines the operations that a persistent job queue driver must implement in order to
 * support enqueuing, processing, and tracking jobs. It is a low level API responsible only for the persistent storage
 * of jobs and generating a Flow for processing those jobs.
 */
public interface QueueDriver<JobMetadata : Any> {

// Insert/Query Operations
// ---------------------------------------------------------------------------------------------------------------------

    /**
     * Adds an item to the queue. All properties of a [SerializedJob] must be provided except for the ID, which will be
     * generated by the driver and returned to the caller. The job is inserted into a specific queue by name.
     *
     * This function should return a String representation of the job's unique ID.
     */
    public suspend fun addToQueue(
        queueName: String,
        serializedPayload: String,
        serializedInitialState: String,
        timeoutDuration: Duration,
        metadata: JobMetadata,
    ): String

    /**
     * Observe a flow of jobs from the queue. Items emitted to the flow should not be removed from the queue, since its
     * state of the job will be updated in-place.
     */
    public fun observeQueue(
        queueName: String,
    ): Flow<SerializedJob<JobMetadata>>

// Job Processing State/Results
// ---------------------------------------------------------------------------------------------------------------------

    /**
     * The job state was updated while processing the job. If a job is retried, the state will be maintained between attempts.
     */
    public suspend fun updateJobState(
        jobId: String,
        serializedState: String,
    )

    /**
     * The job ran to completion, which may have been successful or failure. The processing time and result
     * (success, failure, retry) are provided so the driver can update the job record appropriately, and optionally
     * enqueue it for retry at a later time.
     */
    public suspend fun markJobCompleted(
        jobId: String,
        processingTime: Duration,
        resultType: JobCompletionResultType,
        serializedResultData: String?,
        retryDelay: Duration?,
        failureMessage: String?,
        failureStacktrace: String?,
    )

// Cancellation
// ---------------------------------------------------------------------------------------------------------------------

    /**
     * Request job cancellation
     */
    public suspend fun requestJobCancellation(jobId: String)

    /**
     * Listen for events from the driver to know when a job was cancelled
     */
    public fun subscribeToJobCancellation(jobId: String): Flow<Unit>
}
