copperleaf.description=Use a PostgreSQL table as the backing store for a Ballast persistent queue in server-side applications.

copperleaf.targets.android=false
copperleaf.targets.jvm=true
copperleaf.targets.ios=false
copperleaf.targets.js=false
copperleaf.targets.wasm.wasi=false
copperleaf.targets.wasm.js=false
